---
version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
    labels:
      - deps
      - go-deps
    reviewers:
      - "@arslanbekov"
  - package-ecosystem: "github-actions"
    directory: "/"
    rebase-strategy: disabled
    schedule:
      interval: daily
    labels:
      - deps
      - gha-deps
    reviewers:
      - "@arslanbekov"